version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      # start pancakedb server
      - run:
          name: Running PancakeDB server
          command: npm run start
          background: true

      - run: sleep 1

      # run tests!
      - run: npm run test